Dami/implement neighbor root polling
webb-tools/protocol-substrate pull request #194
Opened 2022-04-26 21:02 UTC by dharjeezy

make use of default root

2022-04-27 14:26 UTC, drewstone requested changes
LGTM! Let's move the default hashes into the chain spec / genesis configuration. I think that would be an improvement greatly needed.

2022-04-27 14:26 UTC, drewstone commented on primitives/src/traits/merkle_tree.rs
> +	fn zero_root(i: u8) -> Result<[u8; 32], dispatch::DispatchError>;
Can we add documentation to this?

2022-04-27 14:26 UTC, drewstone commented on primitives/src/traits/linkable_tree.rs
> +	fn zero_root(i: u8) -> Result<[u8; 32], dispatch::DispatchError>;
Documentation, describe what the zero root is.

2022-04-28 21:16 UTC, dutterbutter commented on pallets/linkable-tree/src/lib.rs
> +pub type DefaultMerkleRootIndexOf<T, I> = <T as pallet_mt::Config<I>>::DefaultMerkleRootIndex;
Please add a brief definition to public type.

2022-04-29 09:51 UTC, drewstone requested changes
Looks good! I would remove usage of default hashes since that is what was previously used. We shouldn't need it anymore assuming you are relying on this new collection. Therefore, we'd want to remove wherever it's called/creates/queries and replace with the new one.

2022-04-29 09:51 UTC, drewstone commented on pallets/linkable-tree/src/lib.rs
> +			if edges.len() <= max_edges {
Should be <, no?

2022-04-29 09:51 UTC, drewstone commented on pallets/mt/src/lib.rs
> +				default_hashes: None,
Redundant

2022-05-03 17:44 UTC, closed without merging