add scaffold for anon mining miner
webb-tools/protocol-substrate pull request #280
Opened 2022-12-21 05:55 UTC by kwhuo68

**Summary of changes**
Changes introduced in this pull request:
-Anonymity mining Miner contract functionality

2023-01-09 17:46 UTC, drewstone commented
@kwhuo68 what's the status of this?

2023-01-09 20:43 UTC, kwhuo68 commented
> @kwhuo68 what's the status of this?

Paused this - working on https://github.com/webb-tools/protocol-solidity/pull/225 which should be ready for review soon

2023-02-08 15:56 UTC, drewstone commented on pallets/anonymity-mining/src/lib.rs
> +	pub type TornadoTrees<T: Config<I>, I: 'static = ()> =
```suggestion
	pub type RewardTrackingTrees<T: Config<I>, I: 'static = ()> =
```

2023-02-08 15:57 UTC, drewstone requested changes
What's the status of this @kwhuo68 ?

2023-03-27 15:49 UTC, closed without merging