add reward pallet modifications
webb-tools/protocol-substrate pull request #288
Opened 2023-01-27 16:04 UTC by kwhuo68

**Summary of changes**
Changes introduced in this pull request:
-Scaffold for pallet modifications for rewards (AP VAnchor updating, etc)

2023-02-08 17:06 UTC, drewstone commented
@saiakilesh good to merge if you review and give it the go ahead.

2023-02-08 17:46 UTC, saiakilesh reviewed
Along, with my comments on specific lines of code, here are a few overarching things:
1. We have renamed things: `DepositTree` -> `UnspentTree`, `WithdrawTree -> SpentTree`.
1. I would rather separate concerns and have two different pallets, a claims pallet and an AMM pallet. The claims pallet is responsible for storing reward tree roots, checking claims circuit proof, and inserting commitments into the AP VAnchor. The AMM pallet is responsible for converting AP into Tangle tokens (or whatever the reward token is).

2023-02-08 17:46 UTC, saiakilesh commented on pallets/anonymity-mining/src/lib.rs
> +			T::VAnchor::update_edge(
The APVAnchor is stored only on Substrate. It does not need its edges to be updated.

2023-02-08 17:46 UTC, saiakilesh commented on pallets/anonymity-mining/src/lib.rs
> +		// Update roots
I don't understand why we are updating the deposit / withdraw tree roots twice for a `src` and `dest`. Can you please explain? In my opinion, we should have two functions, one for inserting into the cached deposit root storage and one for inserting into the cached withdraw root storage.

2023-02-08 17:46 UTC, saiakilesh commented on pallets/anonymity-mining/src/lib.rs
> +		Self::update_roots(
Why are you updating the cached deposit/withdraw tree roots when claiming AP?

2023-02-08 17:46 UTC, saiakilesh commented on pallets/anonymity-mining/src/lib.rs
> +		Self::handle_proof_verification(&proof_data)?;
Shouldn't this line be at the beginning of the function? We have to check the proof first, before doing anything else.

2023-02-08 17:46 UTC, saiakilesh commented on pallets/anonymity-mining/src/lib.rs
> +		<T as Config<I>>::Currency::transfer(
Claiming AP only consists of inserting a commitment into the APVAnchor, we shouldn't transfer any tokens.

2023-02-14 14:26 UTC, saiakilesh requested changes
`deposit -> unspent`, `withdraw -> spent`

2023-02-14 14:26 UTC, saiakilesh commented on pallets/anonymity-mining-claims/src/lib.rs
> +		Self::update_deposit_root(deposit_tree_id, deposit_root_index, deposit_root);
Again, not sure why updating deposit/withdraw roots while claiming.

2023-02-14 14:26 UTC, saiakilesh commented on pallets/anonymity-mining-claims/src/lib.rs
> +		for nullifier in &proof_data.input_nullifiers {
Need to also store the withdraw tree nullifier hashes.

2023-02-14 14:26 UTC, saiakilesh commented on pallets/anonymity-mining-claims/src/lib.rs
> +			T::LinkableTree::insert_in_order(deposit_tree_id, *comm)?;
Why are you inserting into deposit tree instead of AP VAnchor?

2023-02-21 18:31 UTC, merged