[fix] address SBP fixes - part 2
webb-tools/protocol-substrate pull request #291
Opened 2023-02-07 18:32 UTC by 1xstj

**Summary of changes**
Changes introduced in this pull request:
- Remove transactional macro
- Handle all unsafe arithmetic and unwrap()
- Fix all failing benchmarks
- Add benchmark check to CI
- Add taplo config to format toml files

**Reference issue to close (if applicable)**
Closes https://github.com/webb-tools/protocol-substrate/pull/283

2023-02-08 17:07 UTC, drewstone commented
CI failing here @1xstj

2023-02-19 09:54 UTC, drewstone requested changes
We have inconsistent spacing in the `Cargo.toml` files, some using 4 spaces, some using tabs, some using 2 spaces.

2023-02-19 09:54 UTC, drewstone commented on standalone/node/Cargo.toml
> +                     "frame-benchmarking/runtime-benchmarks",
Spacing

2023-02-21 13:19 UTC, shekohex approved these changes

2023-02-22 07:57 UTC, merged