Linkable tree
webb-tools/protocol-substrate pull request #48
Opened 2021-11-03 11:25 UTC by lazovicff

2021-11-04 14:17 UTC, drewstone requested changes
Looks good so far!

2021-11-04 14:17 UTC, drewstone commented on pallets/anchor/src/lib.rs
> -	fn add_edge(
Can we keep these functions mocked through the `T::LinkableTree` interface?

2021-11-04 14:17 UTC, drewstone commented on pallets/anchor/src/lib.rs
> -	fn update_edge(
Can we keep these functions mocked through the `T::LinkableTree` interface?

2021-11-04 14:17 UTC, drewstone commented on pallets/linkable-tree/src/types.rs
> +pub struct AnchorMetadata<AccountId, Balance> {
This probably isn't needed here? Metadata should be kept on `pallet-anchor`

2021-11-04 17:48 UTC, filiplazovic commented
This is almost done, but I'm not sure we achieved our goal completely since edge updates are done through the anchor (the app). wdyt @drewstone

2021-11-04 17:49 UTC, drewstone commented
I think I actually prefer it this way. I want the anchor to be where we
update add the edges but like the implementation is abstracted downstream.

On Thu, Nov 4, 2021 at 1:48 PM Filip Lazovic ***@***.***>
wrote:

> This is almost done, but I'm not sure we achieved our goal completely
> since edge updates are done through the anchor (the app). wdyt @drewstone
> <https://github.com/drewstone>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/webb-tools/protocol-substrate/pull/48#issuecomment-961279010>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADELLF3GADE3QBYAXR45G7DUKLBOTANCNFSM5HIVNM5A>
> .
>

2021-11-05 16:02 UTC, filiplazovic commented
@drewstone This is ready

2021-11-08 16:01 UTC, merged