adds new deps.
webb-tools/protocol-substrate pull request #61
Opened 2021-11-30 19:47 UTC by mfaghihi

2021-12-02 00:02 UTC, drewstone commented on node/Cargo.toml
> +arkworks-gadgets = { version = "0.4.1", features = ["std", "r1cs"], default-features = false }
Worth bumping to 0.4.2

2021-12-02 14:52 UTC, drewstone commented on node/Cargo.toml
> +arkworks-gadgets = { version = "0.4.1", features = ["std", "r1cs"], default-features = false }
Need to remove features as well.

2021-12-02 14:54 UTC, drewstone requested changes
The runtime does not support the std library. Therefore you can't add these types of features here. You have to ensure there are no std dependencies in these crates or else everything will break.

2021-12-02 14:54 UTC, drewstone commented on pallets/anchor/Cargo.toml
> +arkworks-gadgets = { version = "0.4.1", features = ["std", "r1cs"], default-features = false }
Need to remove features.

2021-12-02 14:54 UTC, drewstone commented on pallets/anchor/Cargo.toml
> +arkworks-circuits = { version = "0.4.1", features = ["std", "r1cs"], default-features = false }
Need to remove features.

2021-12-02 14:54 UTC, drewstone commented on pallets/anchor/Cargo.toml
> +arkworks-utils = { version = "0.4.1", features = ["std", "r1cs"], default-features = false }
Need to remove features.

2021-12-02 14:54 UTC, drewstone commented on node/Cargo.toml
> +arkworks-gadgets = { version = "0.4.1", features = ["std", "r1cs"], default-features = false }
Need to remove features.

2021-12-02 14:54 UTC, drewstone commented on pallets/anchor/zk-setup/Cargo.toml
> +arkworks-gadgets = { version = "0.4.1", features = ["std", "r1cs"], default-features = false }
Need to remove features. And in the rest of the deps.

2021-12-04 19:01 UTC, drewstone commented
Is this ready for merge @mfaghihi ? We'll need a Pr updating the branches to versions also once this is merged since it points to a git branch.

2021-12-06 18:06 UTC, filiplazovic approved these changes

2021-12-06 19:17 UTC, merged